version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql    
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
  app:
    build: .
    image: chatapplication
    container_name: app
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
      QUEUE: "*"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST: "redis://redis"
      RAILS_LOG_TO_STDOUT: "yes"
      # RAILS_ENV: "development" 
      RAILS_ENV: "production" 
    depends_on:
      - mysql
      - es-mapping-init
      - redis
    volumes:
      - .:/app
      - /app/data
    command: start.sh
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es-mapping-init:
    build: es-mapping-init
    depends_on:
      - es